### PR TITLE
fix: Adding processing of unrecoverable deployment conditions

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### What does this PR do?
Adding processing of unrecoverable deployment conditions

### What issues does this PR fix or reference?

https://github.com/devfile/devworkspace-operator/issues/685
https://github.com/eclipse/che/issues/20821

### Is it tested? How?

- apply quota to a namespace where the devWorkspace is going to be created e.g.

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-long-running
spec:
  hard:
    pods: "4" 
    limits.cpu: "1" 
    limits.memory: "1Gi" 
  scopes:
  - NotTerminating 
 ```
- create a devWorkspace with high CPU / RAM limits

```
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: spring-petclinick
spec:
  started: true
  template:
    projects:
      - name: sprint-petclinick
        git:
          remotes:
            origin: "https://github.com/benoitf/spring-petclinic/tree/error-cpu.git"
    components:
    ### BEGIN Contributions from Theia plugin ###
      - name: tools
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-d433ed6
          memoryRequest: 32Mi
          memoryLimit: 3Gi
          cpuLimit: 3000m
          cpuRequest: 100m
          endpoints:
            - exposure: none
              name: debug
              protocol: tcp
              targetPort: 5005
            - exposure: public
              name: 8080-tcp
              protocol: http
              targetPort: 8080
          volumeMounts:
            - name: m2
              path: /home/user/.m2

      - name: m2
        volume:
          size: 1G
      
      - name: mysql
        container:
          image: quay.io/eclipse/che--centos--mysql-57-centos7:latest-e08ee4d43b7356607685b69bde6335e27cf20c020f345b6c6c59400183882764
          memoryLimit: 300Mi
          endpoints:
            - exposure: none
              name: db
              protocol: tcp
              targetPort: 3306
          env:
            - name: MYSQL_USER
              value: petclinic
            - name: MYSQL_PASSWORD
              value: petclinic
            - name: MYSQL_DATABASE
              value: petclinic
            - name: PS1
              value: $(echo ${0})\\$

    commands:
      - id: prepare-database
        exec:
          component: mysql
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: |
            /opt/rh/rh-mysql57/root/usr/bin/mysql -u root < ${PROJECTS_ROOT}/java-spring-petclinic/src/main/resources/db/mysql/user.sql && \
            /opt/rh/rh-mysql57/root/usr/bin/mysql -u root petclinic < ${PROJECTS_ROOT}/java-spring-petclinic/src/main/resources/db/mysql/schema.sql && \
            /opt/rh/rh-mysql57/root/usr/bin/mysql -u root petclinic < ${PROJECTS_ROOT}/java-spring-petclinic/src/main/resources/db/mysql/data.sql && \
            echo -e "\e[32mDone.\e[0m Database petclinic was configured"
          group:
            kind: run
            isDefault: true

      - id: build
        exec:
          component: tools
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: mvn clean install
          group:
            kind: build
            isDefault: true

      - id: run-with-hsqldb
        exec:
          component: tools
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: >-
            java -jar target/*.jar
          group:
            kind: run
            isDefault: true

      - id: run-with-mysql
        exec:
          component: tools
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: |
            java -jar -Dspring-boot.run.profiles=mysql \
            -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 \
            target/*.jar
          group:
            kind: run
            isDefault: true

      - id: run-debug
        exec:
          component: tools
          workingDir: ${PROJECTS_ROOT}/java-spring-petclinic
          commandLine: >-
            java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 target/*.jar
          group:
            kind: run
            isDefault: true
```
- follow up on the dw state:

```
devworkspace.workspace.devfile.io/spring-petclinick created
[ibuziuk@fedora devworkspace-operator]$ oc get dw
NAME                DEVWORKSPACE ID             PHASE      INFO
spring-petclinick   workspace5f3020fb221441dd   Starting   Waiting for workspace deployment
[ibuziuk@fedora devworkspace-operator]$ oc get dw
NAME                DEVWORKSPACE ID             PHASE    INFO
spring-petclinick   workspace5f3020fb221441dd   Failed   Detected unrecoverable deployment condition: FailedCreate pods "workspace5f3020fb221441dd-59f5dfc6-vxt6n" is forbidden: failed quota: compute-resources-long-running: must specify limits.cpu
```

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]
LGTM

**Review by amisevsk — APPROVED** [review]
LGTM, will test tomorrow.

**Comment by ibuziuk** [comment]
@amisevsk how this PR can be merged? merge button is disabled due to prow e2e pending state :man_shrugging:

**Pull request merged**
