### PR TITLE
Build OLM bundle and index on releases

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Adds steps to `make-release.sh` to automatically build and push a suitable bundle + index image to quay.

Detailed changes:
* Generate `relatedImages` in the CSV 
* Update `opm` to `v1.19.1`
* Switch upstream bundle + index build to use a [file-based catalog](https://olm.operatorframework.io/docs/tasks/creating-a-catalog/), introduced in `opm v1.19.0`
    * This requires storing additional metadata files in the repo and adds a couple of manual steps to the release process
* Build _one_ index for releases that gets updated and includes update paths from previous releases.

### What issues does this PR fix or reference?
This allows us to release an upstream index + bundle for the operator.

### Is it tested? How?
```bash
# Set these env vars to avoid pushing to main repos
export DWO_QUAY_REPO="quay.io/amisevsk/devworkspace-controller-test"
export PROJECT_CLONE_QUAY_REPO="quay.io/amisevsk/project-clone-test"
export DWO_BUNDLE_QUAY_REPO="quay.io/amisevsk/devworkspace-operator-bundle-test"
export DWO_INDEX_IMAGE="quay.io/amisevsk/devworkspace-operator-index-test:release"

# Setup local repo with dummy "remote" to avoid pushing changes to GitHub
cd $(mktemp -d)
git clone git@github.com:amisevsk/devworkspace-operator
mkdir devworkspace-upstream
cd devworkspace-upstream && git init --bare
cd ../devworkspace-operator

# Merge this PR to main
git merge origin/build-bundle-release
git remote set-url origin ../devworkspace-upstream
git push origin main

# Do prerelease for v0.11.0
./make-release.sh --prerelease --version v0.11.0
git checkout 0.11.x

# Manually add `replaces` field to CSV (required)
yq -Yi '.spec.replaces = "devworkspace-operator.v0.10.0"' \
  deploy/templates/components/csv/clusterserviceversion.yaml \
  deploy/bundle/manifests/devworkspace-operator.clusterserviceversion.yaml
git commit -am 'add .spec.replaces to CSV'

# Release v0.11.0
./make-release.sh --release --version v0.11.0
```
Once complete, check the commits in `main` and `0.11.x` to ensure fields/versions/images are set correctly.

A built index for a fake `v0.11.1` release is available at https://quay.io/repository/amisevsk/devworkspace-operator-index-test; I haven't fully tested installing/upgrading the operator using it yet, but will do that next week.

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]
I haven't tested the created index but I ran the test scenario and everything seem to work correctly

**Comment by amisevsk** [comment]
Holding off on merging this as I tested the built index and, while it appears correct on the cluster no Operators are listed inside of it.

**Comment by amisevsk** [comment]
Blocked as changes in https://github.com/operator-framework/operator-registry/pull/807 are required in `opm` for the index image to function correctly. These changes haven't been propagated to a release yet and are unavailable.

**Comment by amisevsk** [comment]
/test v8-devworkspace-operator-e2e, v8-che-happy-path

Reworked to use the old way (`opm index add ...`) for now. Tested the latest commit (with an index built the _old_ way) and it works properly. Image is `quay.io/amisevsk/devworkspace-operator-index-test:release
` (same as previous).

**Comment by amisevsk** [comment]
Testing the catalog with the new image:
```yaml
oc new-project devworkspace-operator-test
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dwo-test
EOF

cat <<EOF | oc apply -f - 
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-devworkspace-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/amisevsk/devworkspace-operator-index-test:release
  publisher: Red Hat
  displayName: DevWorkspace Operator Catalog
EOF

cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devworkspace-operator
spec:
  channel: fast
  name: devworkspace-operator
  source: custom-devworkspace-operator-catalog
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
  startingCSV: devworkspace-operator.v0.10.0
EOF
```
Then, approve the v0.10.0 install (which will install the actual v0.10.0 release), test that DWO works correctly, approve the v0.11.0 install (built from current master) and test that DWO upgrades smoothly and continues to work.

In testing this myself, I noticed that my running DevWorkspace was restarted; it's unclear why at the moment.

**Comment by amisevsk** [comment]
/retest

looks like a cluster-level failure.

**Review by JPinkney — APPROVED** [review]
Just re-tested with the changes from https://github.com/devfile/devworkspace-operator/pull/672#issuecomment-967743808 and everything worked succesfully

**Pull request merged**
