### PR TITLE
Add "patch secrets" to workspace SA RBAC

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Add the `patch secrets` permission to the default workspace SA RBAC.

### What issues does this PR fix or reference?
Required for some use cases that depend on this secret.

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]

**Review by JPinkney — CHANGES_REQUESTED** [review]
Moving from approved to request changes because I'm not sure if storing everything inside of workspace-credentials-secrets is the right choice in the context of https://github.com/eclipse/che/issues/20749. To me, it seems like we should be working with a seperate workspace preferences configmap instead

**Comment by amisevsk** [comment]
Added `workspace-preferences-configmap` to the workspace RBAC set :tada:

**Review by JPinkney — APPROVED** [review]

**Comment by vinokurig** [comment]
Please do not merge until https://github.com/eclipse-che/che-server/pull/174 is merged. This PR is supposed to add the `workspace-preferences-configmap`.

**Comment by amisevsk** [comment]
@vinokurig are you sure there is a blocker for merging this PR? it's purely additive, so merging it shouldn't break anything elsewhere.

Is the concern that the added RBAC may have to be modified? I'm asking because once the Prow issues are resolved, I'd like to begin the v0.11 release process as soon as possible, and I'd like for v0.11 to include these changes (otherwise Theia is waiting for v0.12 in ~5 weeks).

**Pull request merged**
