### PR TITLE
Reformat variable using spaces as indentation for directives

### PR DESCRIPTION
**Pull request by amisevsk**
This PR makes _writing_ the Makefiles a little more tedious (since the new convention is mixing tabs and spaces) but maybe easier to read. Not sure if it's worth merging.

### What does this PR do?
Reformat the Makefiles (since I realized Make directives can be safely indented using spaces):
* Nested directives are indented using spaces, so that e.g.
    ```make
    # minikube handling
    ifeq ($(shell $(K8S_CLI) config current-context 2>&1),minikube)
    # check ingress addon is enabled
    ifeq ($(shell minikube addons list -o json | jq -r .ingress.Status), disabled)
    $(error ingress addon should be enabled on top of minikube)
    endif
    export ROUTING_SUFFIX := $(shell minikube ip).nip.io
    endif
    ```
    becomes
    ```make
    # minikube handling
    ifeq ($(shell $(K8S_CLI) config current-context 2>&1),minikube)
      # check ingress addon is enabled
      ifeq ($(shell minikube addons list -o json | jq -r .ingress.Status), disabled)
        $(error ingress addon should be enabled on top of minikube)
      endif
      export ROUTING_SUFFIX := $(shell minikube ip).nip.io
    endif
    ```
    (note this indentation is done via spaces -- this breaks markdown syntax parsing but should be handled by make okay)
* Reindent regular lines so that first indent is a tab character (as required by Make) and following indentation uses two spaces.

Tested briefly on make `3.81` and indentation seems to cause no issues there either.

### What issues does this PR fix or reference?
Hard to read nested `ifeq`s

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Comment by amisevsk** [comment]
What a silly PR for PR #600 :disappointed:

**Comment by amisevsk** [comment]
Just to get it out of the way:

/test v8-devworkspace-operator-e2e, v8-che-happy-path

**Review by JPinkney — APPROVED** [review]
I personally like this format better then what we currently have. It might take a bit of time to adjust time but it definitely makes the makefiles more readable. I tested all the makefile commands and everything seems to work for me

**Review by sleshchenko — APPROVED** [review]
:+1:

**Pull request merged**
