### PR TITLE
Change tag image on next for getting last changes in the test codebase

### PR DESCRIPTION
**Pull request by musienko-maxim**
### What does this PR do?
Changes the **nightly** tag for the test image on the **next**

### What issues does this PR fix or reference?
eclipse/che#20406 

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspaces-operator-e2e, v8-devworkspace-happy-path` to trigger)
    - [ ] `v8-devworkspaces-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-devworkspace-happy-path`: DevWorkspace e2e test

### CODE REVIEW

**Comment by sleshchenko** [comment]
e2e tests fails because controller fails with

> E0903 14:47:43.754688       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.6/tools/cache/reflector.go:167: Failed to watch *v1beta1.Ingress: failed to list *v1beta1.Ingress: ingresses.extensions is forbidden: User "system:serviceaccount:devworkspace-controller:devworkspace-controller-serviceaccount" cannot list resource "ingresses" in API group "extensions" at the cluster scope

Not sure why it happens. Probably due Josh's image, which should be fixed in https://github.com/devfile/devworkspace-operator/pull/572

**Review by sleshchenko — APPROVED** [review]
LGTM

**Review by JPinkney — APPROVED** [review]

**Comment by sleshchenko** [comment]
happy path test fails due the recent changes how tests deploy DWO, but it's not related to this PR.
So, merging this and prow will get yq and other prerequisites separately.

**Pull request merged**
