### PR TITLE
Fix panic in webhooks server when patching workspace with nil Labels

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Fix a panic that can occur if you try to update a DevWorkspace with nil labels

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v7-devworkspaces-operator-e2e, v7-devworkspace-happy-path` to trigger)
    - [ ] `v7-devworkspaces-operator-e2e`: DevWorkspace e2e test
    - [ ] `v7-devworkspace-happy-path`: DevWorkspace e2e test

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
I assume it can be reproduced only when devworkspace is created before webhooks are set.

**Review by JPinkney — APPROVED** [review]

**Comment by amisevsk** [comment]
> I assume it can be reproduced only when devworkspace is created before webhooks are set.

I thought similar, but I can reproduce this issue in `main` with

```
yq -y '. * {"metadata": {"labels": {"test": "test"}}}' samples/theia-next.yaml \
  | kubectl apply -f -

kubectl apply -f samples/theia-next.yaml
```

:upside_down_face:

**Comment by amisevsk** [comment]
There's an issue in happy-path tests unrelated to this PR:
> ```
> + mv '/tmp/eclipse-che-che-operator-*/deploy' /tmp/che-operator
> mv: cannot stat '/tmp/eclipse-che-che-operator-*/deploy': No such file or directory
> ```

**Pull request merged**
