### PR TITLE
Bump controller-runtime to v0.14.1 and k8s API to v0.26.1

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Updates core dependencies:
      * sigs.k8s.io/controller-runtime to v0.14.1
      * k8s.io/api (et al.) to v0.26.1

Notable changes in the update:
* `corev1.Handler` is replaced with `corev1.LifecycleHandler` and `corev1.ProbeHandler`
* `k8s.io/apimachinery/pkg/util/clock` is replaced with `k8s.io/utils/clock`
* `github.com/go-logr/logr/testing` is deprecated in favor of `github.com/go-logr/logr/testr`

The update also ran into issues around `github.com/redhat-cop/operator-utils`, the latest version of which depends on k8s API `v0.25.0` and controller-runtime `v0.13.0`. Since our usages of this package have been integrated into controller-runtime, the dependency is dropped in favor of these methods (latest versions of operator-utils just wrap the controller-runtime equivalents).

### What issues does this PR fix or reference?
Closes https://github.com/devfile/devworkspace-operator/issues/1059

### Is it tested? How?
N/A

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Comment by amisevsk** [comment]
Before merging this PR, we should do a smoke test against the Che Operator next to ensure the updated k8s API version does not cause issues.

**Comment by AObuchow** [comment]
Code looks good to me :sunglasses:. I had experimented recently with upgrading the controller-runtime to v0.14.1 and am familiar with the API changes that were required (`corev1.LifecycleHandler`, `corev1.ProbeHandler`, `k8s.io/utils/clock` and `github.com/go-logr/logr/testr`).

> Before merging this PR, we should do a smoke test against the Che Operator next to ensure the updated k8s API version does not cause issues.

I'm currently spinning up a cluster to test this out before approving this PR.

**Review by AObuchow — CHANGES_REQUESTED** [review]
The mock client `pkg/library/flatten/internal/testutil/` needs to be modified so that the [`get` function](https://github.com/devfile/devworkspace-operator/blob/main/pkg/library/flatten/internal/testutil/k8sClient.go#L35) has the `opts ...client.GetOption` parameter.

And `testr.New(t)` needs to be used [here](https://github.com/devfile/devworkspace-operator/blob/main/pkg/library/kubernetes/provision_test.go#L102) and [here](https://github.com/devfile/devworkspace-operator/blob/main/pkg/library/kubernetes/provision_test.go#L160)

**Comment by AObuchow** [comment]
I also compiled DWO (..even with the issues in the test files somehow? Maybe go doesn't care if there's compilation issues in the test files) and created + subscribed to the catalog source, and then deployed che:next with chectl and opened up the Che-Website workspace and things worked fine. Though I will repeat this process once the small final changes are made to this PR :)

**Comment by amisevsk** [comment]
ping @AObuchow waiting on approval

**Comment by AObuchow** [comment]
> ping @AObuchow waiting on approval

Going to approve this since everything worked with Che when I last tested this PR even when the tests were broken (since the tests weren't part of the actual DWO image)

**Pull request merged**
