### PR TITLE
Update delve installation instructions. Fix #801

### LINKED ISSUE #801: Outdated instructions on installing delve for local debuging
### Description
In the README's section on local debugging, it is recommended to install delve by doing `go get -u github.com/go-delve/delve/cmd/dlv`. However, this no longer works anymore unfortunately. 

Instead, the README should be modified to instruct users to do `go install github.com/go-delve/delve/cmd/dlv@latest` as mentioned in the [delve installation docs](https://github.com/go-delve/delve/tree/master/Documentation/installation). However, this requires Go 1.16 or later - thus the go dependency in DWO's README should also be updated to mention Go 1.16 or later is required.

I'll submit a PR to update the README.

### How To Reproduce
1. With devworkspace-operator repository cloned, go to the root of the git repository
2. Run `go get -u github.com/go-delve/delve/cmd/dlv`
3. See the error:
```
go: downloading golang.org/x/sys v0.0.0-20220318055525-2edf467146b5
go get: github.com/go-delve/liner@v1.2.2-1 updating to
        github.com/go-delve/liner@v1.2.2: parsing go.mod:
        module declares its path as: github.com/peterh/liner
                but was required as: github.com/go-delve/liner

```

### Expected behavior
Delve should be installed so that `make debug` runs as expected.

### Additional context
After installing delve with `go install github.com/go-delve/delve/cmd/dlv@latest`, running the `dlv` command  requires `$GOPATH/bin` to be added to `PATH` .

I also believe this error is related to https://github.com/go-delve/delve/pull/2905.

### PR DESCRIPTION
**Pull request by AObuchow**
### What does this PR do?
Updates the delve installation instructions for local debugging of DWO.

### What issues does this PR fix or reference?
#801 

### Is it tested? How?
Manual testing.

Checkout the branch, run `go install github.com/go-delve/delve/cmd/dlv@latest` from the repo's root directory after ensuring `$GOPATH` or `$GOBIN` is on `$PATH`, then run `make debug` to ensure DWO is executed in debug mode. 

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Review by amisevsk — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Comment by ibuziuk** [comment]
@AObuchow could you please use the conventional commits - https://www.conventionalcommits.org/en/v1.0.0/#summary
Semantic PR check is failing

**Comment by AObuchow** [comment]
@amisevsk Thanks for merging and review! :partying_face: and thank you @ibuziuk for the review as well!

**Pull request merged**
