### PR TITLE
Increase resource limits for controller to avoid OOMKilled

### PR DESCRIPTION
**Pull request by sleshchenko**
### What issues does this PR fix or reference?
Increase resource limits for controller to avoid OOMKilled

### Is it tested? How?
It's extracted from https://github.com/devfile/devworkspace-operator/pull/296
and it fixes or just workaround https://github.com/devfile/devworkspace-operator/issues/313

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]

**Review by amisevsk — APPROVED** [review]
LGTM, though to be clear, the updated limits are just a guess :)

**Comment by sleshchenko** [comment]
> LGTM, though to be clear, the updated limits are just a guess :)

It's just more stable than currently, but it seems to be a good compromise before requesting 1Gi for controller )

**Pull request merged**
