### PR TITLE
Doc fix 1304

### LINKED ISSUE #1304: [DOC] Operator Descriopion link is broken
The operator description has dead link. Clicking on SPEC 
image
Forward to 404
image

New link: https://devfile.io/docs/2.3.0/devfile-schema

### PR DESCRIPTION
**Pull request by mancubus77**
Fixed #1304 
Update links to API Reference

### CODE REVIEW

**Comment by AObuchow** [comment]
@mancubus77 Thanks for catching this issue and for the PR. Could you please sign-off your commits? They are required for the [DCO check](https://github.com/devfile/devworkspace-operator/pull/1305/checks?check_run_id=28687094901) to pass :)

**Review by AObuchow — APPROVED** [review]
LGTM, testing on OCP 4.16 and installed using OLM. The link now works :)

**Comment by AObuchow** [comment]
@mancubus77 The [DCO check](https://github.com/devfile/devworkspace-operator/pull/1305/checks?check_run_id=28734717005) is still failing with:

> Commit sha: [1fef901](https://github.com/devfile/devworkspace-operator/pull/1305/commits/1fef90117bb054c68bed3e36f9c56b9d66d9c92c), Author: Mancubus, Committer: cerberus; Expected "Mancubus [16170560+mancubus77@users.noreply.github.com](mailto:16170560+mancubus77@users.noreply.github.com)", but got "Ko Sta [sk@redhat.com](mailto:sk@redhat.com)".


Checking your [commit](https://github.com/devfile/devworkspace-operator/pull/1305/commits/1fef90117bb054c68bed3e36f9c56b9d66d9c92c), it seems the author and committer are being recognized as different:
image

You might have success [resetting](https://stackoverflow.com/a/32708751) the author of your commit & setting your git email and name:

```
git config --global user.name "Correct Name" 
git config --global user.email name@email.com 
git commit --amend --reset-author
```

It also might be that your GitHub account's email is not your sk@redhat.com email? If the above doesn't work, I'll dig deeper into this. Sorry for the inconvenience.

**Comment by AObuchow** [comment]
@mancubus77 pinging you to make sure my [earlier comment](https://github.com/devfile/devworkspace-operator/pull/1305#issuecomment-2289868440) didn't get lost in your notifications :)

**Comment by AObuchow** [comment]
@mancubus77 any updates here? Alternatively, I'm happy to push to your fork and signoff the commit in order to resolve the DCO check

**Comment by mancubus77** [comment]
👋  @AObuchow 
Yes please! Happy to have it under your name. 
Thank you, and apologies for the hassle.

**Comment by AObuchow** [comment]
@mancubus77 Sounds great thank you and no worries! I've updated your PR. It should be good to merge once the CI checks finish. Thank you again for your help here :)

**Pull request merged**
