### PR TITLE
fix: Ensure $PROJECT_SOURCE and $PROJECT_ROOT are first environment variables in workspace containers

### PR DESCRIPTION
**Pull request by AObuchow**
### What does this PR do?

Environment variables defined in a Kubernetes container can only reference other variables declared earlier in the list of container environment variables. See the second note from the [Kubernetes docs](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#define-an-environment-variable-for-a-container) on environment variables.
    
This change ensures that the $PROJECT_SOURCE and $PROJECT_ROOT devfile environment variables are the first environment variables defined in all workspace pod containers so that devfile environment variables can reference $PROJECT_SOURCE and $PROJECT_ROOT.

Instead of appending $PROJECT_SOURCE and $PROJECT_ROOT to all workspace containers, we are now prepending them.

Additionally, existing tests were modified to accommodate this change in the list of container environment variables ordering, and a new test was added for this change.

### What issues does this PR fix or reference?
https://github.com/devfile/devworkspace-operator/issues/1274

### Is it tested? How?
1. Install DWO with the changes made from this PR. I've pushed to `quay.io/aobuchow/devworkspace-controller:project-source-first` for ease of testing.
2. Apply the following devworkspace:

```YAML
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: plain-devworkspace-env-test
spec:
  started: true
  routingClass: 'basic'
  template:
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
    components:
      - name: web-terminal
        container:
          image: quay.io/wto/web-terminal-tooling:next
          memoryRequest: 256Mi
          memoryLimit: 512Mi
          mountSources: true
          command:
           - "tail"
           - "-f"
           - "/dev/null"
          env:
           - name: ENV_TEST
             value: $(PROJECT_SOURCE)/hey-there
```
3. Once the workspace starts up, exec into the workspace pod and run `echo $ENV_TEST`. The output should be `/projects/web-nodejs-sample/hey-there` -- in other words, `$(PROJECT_SOURCE)` will get evaluated to `/projects/web-nodejs-sample/`.

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Review by dkwon17 — APPROVED** [review]

**Comment by AObuchow** [comment]
For some reason, the GH Actions aren't running. Will try and do a no-op commit to get it to run, then remove the no-op commit.

**Pull request merged**
