### PR TITLE
Use k8s.io/utils/pointer to instantiate pointers

### LINKED ISSUE #958: Use k8s.io/utils/pointer to instantiate pointers throughout the codebase
### Description
Currently, throughout the DWO repo we are [initializing variables](https://github.com/devfile/devworkspace-operator/blob/main/pkg/config/defaults.go#L52) so that they can be referenced as pointer values when needed, for example [here](https://github.com/devfile/devworkspace-operator/blob/main/pkg/config/defaults.go#L43). 

Instead, we should make use of `k8s.io/utils/pointer` to instantiate pointers and reference them in a single statement.
For example, one can get a pointer that points to a boolean with the value `true` by doing: `pointer.BoolPtr(true)`

### Additional context
Here is where this idea was initially suggested: https://github.com/devfile/devworkspace-operator/pull/953#discussion_r1001981062

### PR DESCRIPTION
**Pull request by PiotrLewandowski323**
### What does this PR do?

Removes some of the variables which are initialized only so that they be referenced as pointer values and replaces their usage with pointers from k8s.io/utils/pointer.

### What issues does this PR fix or reference?
Fixes #958 

### Is it tested? How?

I've run make test and make docker-build. I don't know how I should properly test these changes otherwise.

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Review by amisevsk — APPROVED** [review]
LGTM

Welcome @PiotrLewandowski323 and thanks for your first contribution to the DevWorkspace Operator :smile:

**Comment by amisevsk** [comment]
In case the Che Operator needs to pull in kubernetes/utils in the future, here is the clearlydefined.io entry for the current version: https://clearlydefined.io/definitions/git/github/kubernetes/utils/7d6a63dca704acaa0679df837cea69eabb2e5f67

**Comment by AObuchow** [comment]
> In case the Che Operator needs to pull in kubernetes/utils in the future, here is the clearlydefined.io entry for the current version: [clearlydefined.io/definitions/git/github/kubernetes/utils/7d6a63dca704acaa0679df837cea69eabb2e5f67](https://clearlydefined.io/definitions/git/github/kubernetes/utils/7d6a63dca704acaa0679df837cea69eabb2e5f67)

I actually found out about kubernetes/utils from the Che-Operator codebase :stuck_out_tongue:  good to have that lying around though :+1:

**Review by AObuchow — APPROVED** [review]

**Comment by AObuchow** [comment]
@PiotrLewandowski323 Thank you very much for your PR! :)

**Pull request merged**
