### PR TITLE
Fix temporary vsx-installer entrypoint after adding messages

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Adding a message field to status that contained spaces broke some splitting in the vsx-installer entrypoint. This is a fixup to avoid that issue by setting IFS correctly.

### What issues does this PR fix or reference?
Applying theia-nodejs samples fails.

### Is it tested? How?
`kubectl apply -f samples/flattened_theia-nodejs.yaml`

### CODE REVIEW

**Comment by amisevsk** [comment]
While we should probably just remove these samples, it's still useful to test more advanced functionality occasionally.

**Review by JPinkney — APPROVED** [review]
Works for me :+1:

**Review by sleshchenko — APPROVED** [review]

**Review by sleshchenko — COMMENTED** [review]
Seems on minikube I got 
```
downloading "https://github.com/microsoft/vscode-pull-request-github/releases/download/v0.8.0/vscode-pull-request-github-0.8.0.vsix" to /plugins
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   645  100   645    0     0   4640      0 --:--:-- --:--:-- --:--:--  4640
100  468k  100  468k    0     0   960k      0 --:--:-- --:--:-- --:--:-- 5002k
mkdir: can't create directory 'for': Permission denied

downloading for to for
/bin/sh: can't create for/for: nonexistent directory
mkdir: can't create directory 'deployment': Permission denied

```

**Comment by amisevsk** [comment]
@sleshchenko which sample is this? This makes it look like the PR is a no-op

**Comment by sleshchenko** [comment]
> which sample is this?

It's the key question. It was theia-next. I've added your fix into each place where vsx-installer appears.

**Pull request merged**
