### PR TITLE
Align controller name to be devworkspace-controller

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Align controller name to be devworkspace-controller. It's mainly find/replace:
- workspace-controller
- che-workspace
-> devworkspace

### What issues does this PR fix or reference?
it fixes one item from https://github.com/eclipse/che/issues/17179
CI part is going to be fixed separately.

### Is it tested? How?
```
export IMG=YOU_IMAGE_HERE
export WEBHOOK_ENABLED=true
export DEFAULT_ROUTING=openshift-oauth
export CERT_IMG=YOU_IMAGE_HERE

make docker
make docker_cert
make deploy
# wait until controller is set up
oc apply -f ./samples/cloud-shell.yaml
# make sure that  devworkspace is successfully started
make uninstall

# OR use new e2e_test makefile target
export IMG=YOU_IMAGE_HERE
export WEBHOOK_ENABLED=true
export DEFAULT_ROUTING=openshift-oauth
export CERT_IMG=YOU_IMAGE_HERE

make docker
make docker_cert
make e2e_test
# Make sure that ran tests passed
# Ran 1 of 1 Specs in 102.559 seconds
# SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
```

### CODE REVIEW

**Comment by sleshchenko** [comment]
> go: github.com/openshift/api@v3.9.1-0.20190424152011-77b8897ec79a+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found

What is your `go version`?

**Comment by JPinkney** [comment]
On the computer I just tested on its 1.13.11

**Comment by sleshchenko** [comment]
Anyway - that issue is caused by the already existing command `go mod vendor` that is triggered in bash script. 
So, I would go with merging this as is or just after dropping out `e2e_test` Makefile target

**Comment by sleshchenko** [comment]
@JPinkney 

> On the computer I just tested on its 1.13.11. It might need an upgrade

It should not need since in Dockerfile we use `golang:1.13.7`

**Comment by sleshchenko** [comment]
I excluded e2e_test makefile target and going to merge it.
I'll create another PR for e2e test target

**Pull request merged**
