### PR TITLE
Remove openshift-oauth routingClass and reduce number of images used

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
* Remove openshift-oauth routing and related code (some bits are left -- e.g. rolebinding for oauthClients)
* Remove unused tls secrets creation image and clean up unused constants

### What issues does this PR fix or reference?
Part of https://issues.redhat.com/browse/CRW-1671

### Is it tested? How?
Test as normal; should be no detectable changes except that oauth routing doesn't work.

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
I love CloudShell sample with OpenShift OAuth routing )
But since our implementation does not support correctly multiple ports, and nobody actually use it, +1 to remove it at this point. Bye OpenshiftOAuth routing!

Any reason we kept: some bits are left -- e.g. rolebinding for oauthClients?

**Review by JPinkney — APPROVED** [review]
goodbye openshift-oauth :wave:

**Review by tinakurian — APPROVED** [review]

**Comment by amisevsk** [comment]
> Any reason we kept: some bits are left -- e.g. rolebinding for oauthClients?

We could also remove this, but I wasn't sure if e.g. DWCO needed it. If we're sure the permission is unused, we may as well remove it too :)

**Comment by amisevsk** [comment]
Also went ahead and removed `RELATED_IMAGE_plugin_redhat_developer_web_terminal_4_5_0` since nothing was using it.

**Comment by sleshchenko** [comment]
> Also went ahead and removed RELATED_IMAGE_plugin_redhat_developer_web_terminal_4_5_0 since nothing was using it.

really? e2e tests fail with

> OpenShift Web terminal workspace didn't start properly. Error: workspace has been failed unexpectedly

> NAME           DEVWORKSPACE ID             PHASE    INFO
web-terminal   workspacef4854772f1d94263   Failed   Error processing devfile: failed to read plugin for component web-terminal from internal registry: environment variable RELATED_IMAGE_plugin_redhat_developer_web_terminal_4_5_0 is unset

**Comment by sleshchenko** [comment]
After https://github.com/devfile/devworkspace-operator/pull/383 e2e tests failure cause should be more clear.

**Comment by amisevsk** [comment]
Ah I forgot that we programmatically read the web-terminal RELATED_IMAGEs (I had basically done a `ctrl-f` for `RELATED_IMAGE_plugin_redhat_developer_web_terminal_4_5_0` and found no hits). I'll re-add it :)

**Pull request merged**
