### PR TITLE
chore: Update to ubi8-minimal:8.4-208 and ubi8/go-toolset:1.15.14-3

### PR DESCRIPTION
**Pull request by nickboldt**
Change-Id: I7cd854c30be84ee176322aff508827f80be92c6d
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Review by JPinkney — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Comment by sleshchenko** [comment]
e2e tests failure is really weird https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/devfile_devworkspace-operator/557/pull-ci-devfile-devworkspace-operator-main-v7-devworkspaces-operator-e2e/1432648196160491520
> Downloading devfile/api CRDs to /tmp/tmp.IjaM3cYyk3
Initialized empty Git repository in /tmp/tmp.IjaM3cYyk3/.git/
DevWorkspace API is specified from revision 03e023e7078b64884216d8e6dce8f0cf8b7e74d2
namespace/devworkspace-controller created
ERROR: Program yq is required for this script
Checking for devfile/api CRDs
CRDs from devfile/api are already initialized
Version v4.0.5 does not exist.

@JPinkney any ideas why it happened but previously worked?

**Pull request merged**
