### PR TITLE
Always check if devworkspace CRDs came from current upstream dependency

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Store current `devfile/api` version in directory alongside devfile CRDs. When running the `_init_devworkspace_crds` makefile target, check against this version file and update CRDs if necessary.

Incidentally, also deletes the old `Components` CRD file, which was left over from https://github.com/eclipse-che/che-operator/pull/729

### What issues does this PR fix or reference?
Out-of-date CRDs in all local repos (have to run `make update_devworkspace_crds`) whenever devfile/api version is bumped.

### Is it tested? How?
Run `make _init_devworkspace_crds`; CRDs should be updated and hash should be stored in `deploy/templates/crd/bases/devfile_version`

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
I tested by checkouting `v0.2.3` and using that version

then I switched to main branch
then I had 
```
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
2021-05-04T06:50:43.993Z	INFO	controllers.DevWorkspace	Reconciling Workspace	{"Request.Namespace": "default", "Request.Name": "theia-next", "devworkspace_id": ""}
2021-05-04T06:50:44.002Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "workspace.devfile.io", "reconcilerKind": "DevWorkspace", "controller": "devworkspace", "name": "theia-next", "namespace": "default", "error": "DevWorkspace.workspace.devfile.io \"theia-next\" is invalid: status.workspaceId: Required value"}
```
error

then I switched to `amisevsk:keep-crds-up-to-date` branch

did `make install`
got warning
```
cat: /tmp/devworkspace-operator/deploy/templates/crd/bases/devfile_version: No such file or directory
```

but it worked
```
$ kubectl get dw --all-namespaces                                                                                               
NAMESPACE   NAME         DEVWORKSPACE ID             PHASE      INFO
default     theia-next   workspacef5cbd85232f04398   Running   https://workspacef5cbd85232f04398-theia-3100.192.168.64.64.nip.io
```
thanks 👍

**Comment by amisevsk** [comment]
Force pushed to suppress the warning
```
cat: /tmp/devworkspace-operator/deploy/templates/crd/bases/devfile_version: No such file or directory
```
when the version file does not exist.

**Review by JPinkney — APPROVED** [review]

**Comment by amisevsk** [comment]
`shellcheck` was _very_ unhappy with the repo overall :D 

Fixed now.

**Review by sleshchenko — COMMENTED** [review]
I'm late to the party but LGTM

One thing I'm not sure about - maybe it would be a good idea if we even commit deploy/templates/crd/bases/devfile_version

**Pull request merged**
