### PR TITLE
Fix issues specifying checkoutFrom revision with private projects

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Fixes issues around cloning projects from private repos when `.checkoutFrom.revision` is used. This is done for both SSH keys and personal access tokens:

* For personal access tokens, we parse the `credentials` file from the hard-coded path used by DWO to mount the merged credentials secret, and use the appropriate PAT for the relevant host.
* For SSH keys, we defer to the [ssh_config](https://pkg.go.dev/github.com/kevinburke/ssh_config?utm_source=godoc) library to get the relevant identity file for a host and use that. The library is used since parsing SSH configs is out of scope for project-clone.
    * Currently, if an SSH config specifies multiple identities for a host, only the first is checked. This supports common use cases (including the documented case in [additional-configuration.adoc](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#configuring-devworkspaces-to-use-ssh-keys-for-git-operations))

This PR introduces a new dependency to DWO: https://pkg.go.dev/github.com/kevinburke/ssh_config?utm_source=godoc (MIT License)

### What issues does this PR fix or reference?
Closes https://github.com/devfile/devworkspace-operator/issues/913

### Is it tested? How?
Deploy changes and test various project-clone cases (including that nothing breaks for existing flows):

1. When no auth is configured, public repos can 
    * Clone without revision specified (_current functionality_)
    * Clone and checkout specific revision, from one of remotes (_current functionality_)
2. When PAT secret is configured, private repos specified with https can
    * Clone without revision specified (_current functionality_)
    * Clone and checkout specified revision, from one of remotes (new)
3. When SSH key is configured, private repos specified with SSH can
    * Clone without revision specified (_current functionality_)
    * Clone and checkout specified revision, from one of remotes (new)

To make testing all cases easier, it helps to 1) specify multiple projects in one DevWorkspace, and 2) use ephemeral storage (so that cloning can be triggered by just deleting the workspace pod). Sample DevWorkspace:
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: plain-devworkspace
spec:
  started: true
  routingClass: 'basic'
  template:
    attributes:
      controller.devfile.io/storage-type: ephemeral
    projects:
      - name: private-repo-ssh
        git:
          remotes:
            origin: git@github.com:your/private/repo.git
          checkoutFrom:
            revision: private-revision
      - name: private-repo-https
        git:
          remotes:
            origin: https://github.com/your/private/repo.git
          checkoutFrom:
            revision: private-revision
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
      - name: devworkspace-operator
        git:
          checkoutFrom:
            remote: amisevsk
            revision: git-branch-private-repo
          remotes:
            origin: "https://github.com/devfile/devworkspace-operator.git"
            amisevsk: "https://github.com/amisevsk/devworkspace-operator.git"
    components:
      - name: web-terminal
        container:
          image: quay.io/wto/web-terminal-tooling:next
          memoryLimit: 512Mi
          mountSources: true
          args:
           - "tail"
           - "-f"
           - "/dev/null"
```
Then to test e.g. private SSH repos _without_ a revision, you can edit the DevWorkspace to remove `checkoutFrom` and delete the workspace pod.

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Comment by amisevsk** [comment]
Changes can be tested on an existing DWO installation by setting `RELATED_IMAGE_project_clone` to `quay.io/amisevsk/project-clone:private-repos` in the controller's deployment, or by editing the corresponding field in the operator's CSV.

**Comment by AObuchow** [comment]
I encountered issues when trying the following two pieces of functionality on OpenShift 4.12:

> - When PAT secret is configured, private repos specified with https can
>    	Clone and checkout specified revision, from one of remotes (new)
> - When SSH key is configured, private repos specified with SSH can
>    	Clone and checkout specified revision, from one of remotes (new)

For a private **https** repo, checking out a specific revision gave the follow log errors in the project clone container:
```
2022/12/15 23:46:04 Using temporary directory /projects/project-clone-2601495925
2022/12/15 23:46:04 Read DevWorkspace at /devworkspace-metadata/flattened.devworkspace.yaml
2022/12/15 23:46:04 Processing project private-repo-https
2022/12/15 23:46:04 Cloning project private-repo-https to /projects/project-clone-2601495925/private-repo-https
Cloning into '/projects/project-clone-2601495925/private-repo-https'...
fatal: unable to get credential storage lock in 1000 ms: Read-only file system
2022/12/15 23:46:05 Cloned project private-repo-https to /projects/project-clone-2601495925/private-repo-https
2022/12/15 23:46:05 Setting up remotes for project private-repo-https
fatal: unable to get credential storage lock in 1000 ms: Read-only file system
2022/12/15 23:46:05 Fetched remote origin at https://github.com/AObuchow/sample-manager.git
2022/12/15 23:46:05 Encountered error while setting up project private-repo-https: failed to checkout revision: failed to read remote origin: authentication required
```
However, checking out a private https repo with a PAT secret worked without a specific revision (i.e omitting `checkoutFrom`)

For a private **ssh** repo, checking out a specific revision gave the following log errors:
```
2022/12/15 23:37:08 Using temporary directory /projects/project-clone-2215838782
2022/12/15 23:37:08 Read DevWorkspace at /devworkspace-metadata/flattened.devworkspace.yaml
2022/12/15 23:37:08 Processing project private-repo-ssh
2022/12/15 23:37:08 Cloning project private-repo-ssh to /projects/project-clone-2215838782/private-repo-ssh
Cloning into '/projects/project-clone-2215838782/private-repo-ssh'...
Warning: Permanently added 'github.com,140.82.112.4' (ECDSA) to the list of known hosts.
2022/12/15 23:37:09 Cloned project private-repo-ssh to /projects/project-clone-2215838782/private-repo-ssh
2022/12/15 23:37:09 Setting up remotes for project private-repo-ssh
2022/12/15 23:37:09 Fetched remote origin at git@github.com:AObuchow/sample-manager.git
2022/12/15 23:37:09 Encountered error while setting up project private-repo-ssh: failed to checkout revision: failed to read remote origin: error creating SSH agent: "SSH agent requested but SSH_AUTH_SOCK not-specified"
```
Similar to https repo's, checking out the private ssh repo while omitting `checkoutFrom` worked (the existing functionality).

For testing, I used the following devworkspace that includes projects that use a private repo of mine:

```YAML
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: private-repo
spec:
  started: true
  routingClass: 'basic'
  template:
    attributes:
      controller.devfile.io/storage-type: ephemeral
    projects:
      - name: private-repo-ssh
        git:
          remotes:
            origin: "git@github.com:AObuchow/sample-manager.git"
          checkoutFrom:
            revision: experimental
      - name: private-repo-https
        git:
          remotes:
            origin: "https://github.com/AObuchow/sample-manager.git"
          checkoutFrom:
            revision: copy_folders
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
      - name: devworkspace-operator
        git:
          checkoutFrom:
            remote: amisevsk
            revision: git-branch-private-repo
          remotes:
            origin: "https://github.com/devfile/devworkspace-operator.git"
            amisevsk: "https://github.com/amisevsk/devworkspace-operator.git"
    components:
      - name: web-terminal
        container:
          image: quay.io/wto/web-terminal-tooling:next
          memoryLimit: 512Mi
          mountSources: true
          args:
           - "tail"
           - "-f"
           - "/dev/null"
```

The PAT secret I used has the following form (based off of [this](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#adding-git-credentials-to-a-workspace):

```
kind: Secret
apiVersion: v1
metadata:
  name: git-credentials-secret
  annotations:
    controller.devfile.io/mount-path: /tmp/.git-credentials/
  labels:
    controller.devfile.io/git-credential: 'true'
    controller.devfile.io/watch-secret: 'true'
data:
  credentials:  https://aobuchow:{PERSONAL_ACCESS_TOKEN}@github.com/AObuchow/sample-manager.git
```
The credentials were base64 encoded.

Looking at it now... it's possible my username at the start is incorrect (It's AObuchow not aobuchow). However, this wouldn't really explain why I was able to clone the https repo when omitting the `checkoutFrom` field.

For ssh auth, I created a new SSH key pair and uploaded the public key to my GitHub account and followed [these instructions](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#configuring-devworkspaces-to-use-ssh-keys-for-git-operations)

Sorry for not posting the project clone container logs from when things worked (when omitting the `checkoutFrom` field) as my cluster has expired.

**Comment by amisevsk** [comment]
@AObuchow just to double check -- this is while running a project-clone container built off this PR (e.g. `quay.io/amisevsk/project-clone:private-repos`), right? The logs posted suggest this PR has made zero changes :thinking:

**Comment by AObuchow** [comment]
[> @AObuchow just to double check -- this is while running a project-clone container built off this PR (e.g. `quay.io/amisevsk/project-clone:private-repos`), right? The logs posted suggest this PR has made zero changes :thinking: 

Oops - I had done a `make docker build` on this branch for my own quay repo, assuming that would work as well. This was likely the cause of the issue. I will verify once I get a chance, sorry  about that.

**Comment by amisevsk** [comment]
Yeah, to test building the changes you need to specifically build the project-clone container
```
podman build -t <IMAGE_TAG> -f ./project-clone/Dockerfile .
```

**Review by AObuchow — APPROVED** [review]
Code looks good to me & was able to get all new and existing functionality working as expected :+1: 

Originall, I had mistakenly used the wrong format for my git credentials, the correct format is:
`https://AObuchow:{PERSONAL_ACCESS_TOKEN}@github.com`

(emphasis on the `github.com` ending rather than `github.com/{repo-name}.git`, didn't read the documentation correctly :P )

**Review by dkwon17 — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
