### PR TITLE
Start building offline-compatible operator indexes

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Update the `next` and `release` flows to additionally build offline-compatible catalogs that use image digests instead of tags.

The way this is done is by first building the usual bundle, then converting it to a digest bundle by
1. Copying the manifests out of it
2. Replacing all image references with digests
3. Building a new bundle from the updated manifests and pushing it
4. Rendering the new bundle into a new file-based catalog.

This PR also adds an initial entry for DWO 0.21.1 and pushes a new images:
* `quay.io/devfile/devworkspace-operator-bundle:v0.21.1-digest` -- airgap compatible bundle for the v0.21.1 release
* `quay.io/devfile/devworkspace-operator-index:release-digest` -- airgap compatible index. Currently contains _only_ the 0.21.1 release, but should permit upgrades from any installed version of DWO to v0.21.1

For future releases, new bundles should be added to the `quay.io/devfile/devworkspace-operator-index:release-digest` image automatically.

Untested as of this PR is the update to the next GH workflow -- the intention is to take the built `next` bundle, convert it to a digests bundle, push it to `next-digest`, and build a catalog from that after building the usual next catalog.

### What issues does this PR fix or reference?
Closes https://github.com/devfile/devworkspace-operator/issues/1119

### Is it tested? How?
To test the releases index, you can use the catalogsource 
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devworkspace-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/devfile/devworkspace-operator-index:release-digest
  publisher: Red Hat
  displayName: DevWorkspace Operator Catalog
  updateStrategy:
    registryPoll:
      interval: 5m
```
This index should support installing DWO v0.21.1, as well as support upgrading from any already-installed version <0.21.1 of DWO to v0.21.1

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Comment by amisevsk** [comment]
cc: @tolusha this is a follow up to your PR https://github.com/devfile/devworkspace-operator/pull/1035 -- I've reworked the original script you provided into `build_digests_bundle.sh`. Please review if you have a chance (I can't request review from you)

**Comment by AObuchow** [comment]
I was able to install DWO from OperatorHub by using the provided catalogsource, but trying to upgrade from DWO 0.20.0 (installed from OperatorHub) gave an error about causing conflicts with the DWO CRDs:

image

**Comment by amisevsk** [comment]
@AObuchow that's not an upgrade, that's a separate install (you can't install two operators that "control" the same CRD).

To upgrade an operator, you can change the subscription in the cluster to point at the other catalog source. If the other catalog has a newer version that can be upgraded from the previous, you should see an upgrade available.

**Comment by amisevsk** [comment]
Now to see if the `next` build goes as expected :crossed_fingers:

**Pull request merged**
