### PR TITLE
Rename sample catalog source for simplicity

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Renames DWO catalogsource so it's more obvious how to use it when creating a subscription manually.

### What issues does this PR fix or reference?
Nitpick

### Is it tested? How?
N/A

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Review by JPinkney — COMMENTED** [review]
I think you might have to update `make unregister_catalogsource` as well in `olm.mk`

**Comment by amisevsk** [comment]
Good catch! Updated.

**Review by JPinkney — APPROVED** [review]

**Pull request merged**
