### PR TITLE
chore: update commit template to use...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: update commit template to use semantic commit (#19912)

Change-Id: I7ed600fa774be58444cca0d3ba93fdc7c2f58fe7
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by amisevsk — APPROVED** [review]

**Comment by amisevsk** [comment]
Though note that semantic commits are not required in this repo, and we generally ignore the requirement (I don't have permissions to remove the plugin).

**Comment by nickboldt** [comment]
Yeah, I often accept PRs that don't use them too. But this is just one less red x on PRs, so they're easier to at-a-glance approve. 

Meanwhile... waiting on prow...

**Comment by amisevsk** [comment]
@nickboldt you're also free to request a prow CI run (the template used for these PRs overwrites the helpful default hint)

/test v8-devworkspace-operator-e2e

FWIW, I'd sooner just remove semantic PRs from this repo than prefix all these commits with `chore: release: bump`. Looks significantly uglier than `[release]` to me.

**Comment by benoitf** [comment]
@amisevsk FYI when reviewing all merged PR weekly we are filtering out PR title based on semantic commits, so it's really helpful to have these prefix.

**Pull request merged**
