### PR TITLE
[feat] Provision user and email credentials to gitconfig

### PR DESCRIPTION
**Pull request by JPinkney**
Signed-off-by: Josh Pinkney <joshpinkney@gmail.com>

### What does this PR do?
This PR automatically provisions user and email credentials to the gitconfig whenever the label: controller.devfile.io/git-user-credential is true.

If you want to provision git credentials to your gitconfig you can use:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-user-credentials
  namespace: devworkspace-controller
  labels:
    controller.devfile.io/git-user-credential: "true"
    controller.devfile.io/watch-configmap: "true"
data:
  name: sampleName
  email: sampleName@sampleName.com
```

### What issues does this PR fix or reference?
https://github.com/devfile/devworkspace-operator/issues/694

### Is it tested? How?

Tested manually using the above configmap, but also added unit tests

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Comment by l0rd** [comment]
This is good as first implementation. But rather than a specialized `ConfigMap` for git config username and email we may want to support a new annotation `controller.devfile.io/sub-path` for generic `ConfigMaps` labelled with `controller.devfile.io/mount-to-devworkspace: "true"`. 

That would allow to mount a complete gitconfig (not only user name and email) and to mount any file in an existing folder:. For example:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: git-config-cm
  annotations:
    controller.devfile.io/mount-path: /etc/gitconfig
    controller.devfile.io/sub-path: gitconfig
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
data:
  gitconfig: |
    [user]
      email = jojo@gmail.com
      name = Jojo
    [core]
      editor = vim
    [alias]
      ...
```

**Comment by amisevsk** [comment]
> But rather than a specialized ConfigMap for git config username and email we may want to support a new annotation controller.devfile.io/sub-path for generic ConfigMaps labelled with controller.devfile.io/mount-to-devworkspace: "true".

I beat you to the punch by about an hour :D https://github.com/devfile/devworkspace-operator/pull/710

**Comment by l0rd** [comment]
> I beat you to the punch by about an hour :D #710

I saw that earlier today! I was probably still thinking at the right way to inject a `gitconfig` when you submitted that PR. And you addressed the problem in a simpler way too. That's magic 🧙 🪄  Unfortunately I noticed it too late and I've lost one hour yesterday 😄

**Comment by ibuziuk** [comment]
@amisevsk I believe we can close this one, right?

**Comment by amisevsk** [comment]
I think so, I'll leave the branch in place in case it's needed later as this was initially requested by the Che server IIRC.

**Pull request closed without merging**
