### PR TITLE
Allow read for workspacerouting and watch/list for dw

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Allow read for workspacerouting and watch/list for dw

### What issues does this PR fix or reference?
Fixes https://github.com/devfile/devworkspace-operator/issues/277

### Is it tested? How?
not yet
but the image with this is built as 
`export IMG=sleshchenko/che-workspace-controller:extended-rbac`

### CODE REVIEW

**Comment by benoitf** [comment]
I was able to fetch workspacerouting object from a container inside workspace pod with this image

```
/projects/tmp $ ./kubectl get workspaceroutings.controller.devfile.io/routing-workspaceeb55021d3cff42e0 -n che
NAME                                AGE
routing-workspaceeb55021d3cff42e0   16d
```

while before I had
```
/projects/tmp $ ./kubectl get workspaceroutings.controller.devfile.io/routing-workspaceeb55021d3cff42e0 -n che
Error from server (Forbidden): workspaceroutings.controller.devfile.io "routing-workspaceeb55021d3cff42e0" is forbidden: User "system:serviceaccount:che:workspaceeb55021d3cff42e0-sa" cannot get resource "workspaceroutings" in API group "controller.devfile.io" in the namespace "che"
```

**Comment by benoitf** [comment]
I think it would be nice to list as well the dev workspaces objects

```
/kubectl get devworkspaces.workspace.devfile.io -n che
Error from server (Forbidden): devworkspaces.workspace.devfile.io is forbidden: User "system:serviceaccount:che:workspaceeb55021d3cff42e0-sa" cannot list resource "devworkspaces" in API group "workspace.devfile.io" in the namespace "che"
```

**Comment by benoitf** [comment]
it's because in the IDE we display a list of other user workspaces:
https://recordit.co/g3buGBrRuk

(but it can be discussed in another issue)

**Comment by benoitf** [comment]
tested image and it's working as expected. Thanks !

**Review by amisevsk — APPROVED** [review]

**Pull request merged**
