### PR TITLE
removing che-rest-api-sidecar

### PR DESCRIPTION
**Pull request by tinakurian**
### What does this PR do?
Removes Che Rest API sidecar

### What issues does this PR fix or reference?
https://github.com/devfile/devworkspace-operator/issues/288

### Is it tested? How?

This is an internal refactor. Ran unit tests

### CODE REVIEW

**Review by amisevsk — APPROVED** [review]
LGTM :+1:

Thanks for catching some weird mistakes along the way (double imports, etc.)

**Review by sleshchenko — COMMENTED** [review]
I'm late on the party :tada: 
LGTM

**Pull request merged**
