### PR TITLE
Remove Component CRD and related code

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Remove the Components CRD. This subresource is unused since https://github.com/devfile/devworkspace-operator/pull/237 but CRDs were left for compatibility. 

### What issues does this PR fix or reference?
Follow up to https://github.com/devfile/devworkspace-operator/pull/237

### Is it tested? How?
Test as normal; should be no functional changes as https://github.com/devfile/devworkspace-operator/pull/237 removed the Components controller.

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
LGTM

We need to sync with deploy team when we change our deployments, ideally we can provide fixes for che operator and chectl

**Comment by sleshchenko** [comment]
It must be merged before the release

**Review by JPinkney — APPROVED** [review]
LGTM

**Pull request merged**
