### PR TITLE
fix: Ignore serviceSpec.ClusterIPs when comparing services to prevent endless routing reconciliation loop

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
The field `clusterIPs` was introduced in Kubernetes 1.20. We're not ignoring it when reconciling the services and because it is automatically set by Kubernetes, it causes a permanent difference between the intended spec and the actual spec preventing the controller from finishing the reconciliation of a devworkspace routing.

### What issues does this PR fix or reference?
N/A

### Is it tested? How?
Only manually.

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v7-devworkspaces-operator-e2e, v7-devworkspace-happy-path` to trigger)
    - [ ] `v7-devworkspaces-operator-e2e`: DevWorkspace e2e test
    - [ ] `v7-devworkspace-happy-path`: DevWorkspace e2e test

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Review by JPinkney — APPROVED** [review]

**Review by amisevsk — APPROVED** [review]

**Comment by sleshchenko** [comment]
from e2e test, devworkspace-controller: 

> panic: ClusterIPs: does not exist
> 
> goroutine 1 [running]:
> github.com/google/go-cmp/cmp/cmpopts.newStructFilter(0x17f82e0, 0xc000448000, 0xc000430e70, 0x3, 0x3, > 0x1a612a0, 0xc000131710, 0x40ae1f, 0x17f82e0)

**Comment by metlos** [comment]
Hmm... so this boils down to the difference in `k8s.io/api` version in che-operator (0.20.6) vs devworkspace-operator (0.18.8).

**Comment by sleshchenko** [comment]
Tests passed. I'll take care of it and sync with PR on devfile/api side

**Comment by sleshchenko** [comment]
I have troubles with updated DWO to https://github.com/devfile/api/pull/565.

Tested the current state and everything seems to work:
- DevWorkspace withing Che;
- WebTerminal including owner only access;
So, triggered Che happy path and going to merge it after it's passed.
Upgrading to devfile with newer k8s/api and controller-runtime is going to be handled in a separate issue https://github.com/devfile/devworkspace-operator/issues/516

**Comment by sleshchenko** [comment]
Happy path passed https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/devfile_devworkspace-operator/504/pull-ci-devfile-devworkspace-operator-main-v7-devworkspace-happy-path/1420344997298835456/artifacts/devworkspace-happy-path/devworkspace-happy-path/build-log.txt, the cluster is being deprovisioned

**Pull request merged**
