### PR TITLE
chore: Add v0.27.0 bundle to main branch

### PR DESCRIPTION
**Pull request by AObuchow**
### What does this PR do?
Adds the v0.27.0 bundle & digest bundle to the main branch.

Based off of the following two commits:
- [Automated commit that added v0.27.0 bundle](https://github.com/devfile/devworkspace-operator/commit/e71a5113c9e886c5ff1c8572160c51156c56deaf)
- [Automated commit that added v0.27.0 bundle digest](https://github.com/devfile/devworkspace-operator/commit/83e421cf9e74ccfb2670bb55e41f0ce2ade57bc1)

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Comment by AObuchow** [comment]
@musienko-maxim any idea why the e2e are failing? Not sure if something changed recently for the prow job

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
