### PR TITLE
codeblock indentation on uninstall instructions

### PR DESCRIPTION
**Pull request by lglussen**
### What does this PR do?
Fixes some markdown rendering in uninstall instructions.  A missing indent (may have been tab/space issue) was causing problems with a code block rendered on the instruction page.  Anyone copying code directly from the code blocks would end up missing 2 terminal commands from step 4.

### What issues does this PR fix or reference?
NA

### Is it tested? How?

View rendering after fix here: https://github.com/lglussen/devworkspace-operator/blob/149a2bbca13049eccd51ea4e1758485b886e69a2/docs/uninstall.md
Look at the step 4 commands.

Compare against current rendering: https://github.com/devfile/devworkspace-operator/blob/main/docs/uninstall.md

### PR Checklist

NA - just a markdown tweak

### CODE REVIEW

**Comment by AObuchow** [comment]
@lglussen Thank you for catching this and submitting a PR :)

**Comment by AObuchow** [comment]
LGTM

**Comment by AObuchow** [comment]
@lglussen Could you please sign off your commit so that the DCO github action passes? i.e `git commit --amend -s` Then you can do a force push `git push -f`

**Comment by amisevsk** [comment]
/test v8-devworkspace-operator-e2e, v8-che-happy-path

(tests are required on all PRs :upside_down_face:)

**Review by ibuziuk — APPROVED** [review]

**Comment by amisevsk** [comment]
The "happy path" test is unhealthy, but DCO is still required (`signed-off-by` footer on commit message). To apply this:
```
git commit --amend -s
<save+exit editor>
git push origin patch-1 -f
```

**Comment by lglussen** [comment]
Sorry for walking away from this - I thought this went through.

**Comment by amisevsk** [comment]
Thanks @lglussen!

**Pull request merged**
