### PR TITLE
Update commands when container contributions are merged

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Rewrite DevWorkspace commands to target the merged component if
* They target a container-contribution component, and
* That contribution is merged into another component in the devfile

This PR treats contributions with apply commands targeting a container contribution as invalid, as it's unclear how to keep the `apply` command valid.

### What issues does this PR fix or reference?
Closes https://github.com/devfile/devworkspace-operator/issues/1029
Related: https://github.com/eclipse/che/issues/21879

### Is it tested? How?
Test cases are added. To test, you can use this [gist](https://gist.githubusercontent.com/amisevsk/a06803a66ac1b938d0cb31969f027037/raw/51b9cf17d71127830ddf169054218ffcc88373b9/sample-contribution.yaml) as a contribution in a DevWorkspace:
```yaml
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: plain-devworkspace
spec:
  started: true
  routingClass: 'basic'
  template:
    components:
      - name: web-terminal
        container:
          image: quay.io/wto/web-terminal-tooling:next
  contributions:
  - name: test-contribution
    uri: https://gist.githubusercontent.com/amisevsk/a06803a66ac1b938d0cb31969f027037/raw/51b9cf17d71127830ddf169054218ffcc88373b9/sample-contribution.yaml
```
Once the workspace is started, verify that the file mounted at `$DEVWORKSPACE_FLATTENED_DEVFILE` matches what is expected (command is updated to target the `web-terminal` component.

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Comment by AObuchow** [comment]
Code looks good to me & nice improvements to the tests :+1: 
Waiting for my cluster to spin up to do some testing.

**Review by AObuchow — APPROVED** [review]
Code looks good to me & manual test case works as expected - the command is re-mapped to the `web-terminal` component in the flattened devfile:

```diff
commands:
  attributes:
    controller.devfile.io/imported-by: test-contribution
  exec:
    commandLine: echo 'hello world'
+    component: web-terminal
  id: test-exec
```

I rebased the PR branch onto main to get the fixes from https://github.com/devfile/devworkspace-operator/pull/1032 so that I could test out the [DevWorkspace](https://gist.github.com/RomanNikitenko/b3771f8ba1f15dee7460cf886b61dc77) related to this issue. Unfortunately, I've been having some issues getting that DevWorkspace to run but I think it's unrelated to this PR - I'll still document what I experienced:

- On OpenShift 4.12, the DevWorkspace was getting an ImagePullBackOff for the Dev container (maybe due to the size of the UDI image).
  - When trying to delete the DevWorkspace, the PVC got stuck in the Terminating state
- On MiniKube, I pre-pulled the UDI image and deployed the workspace, though it didn't progress to the Ready state before timing out.
  - I'm currently increasing the `progressTimeout` field in the DWOC to see if that will help.

**Comment by AObuchow** [comment]
> assuming the fact that the Apply command not being re-mapped is unimportant for that devworkspace).

Trying again on OpenShift, and I can see that the che-code-injection init container terminated succesfully, so it's probably not related to the apply command.

**Comment by amisevsk** [comment]
The `apply` command does not target a merged container, so it should not be remapped -- the flattened DevWorkspace has a container component named `che-code-injector`

**Pull request merged**
