### PR TITLE
chore: re-licensing Devfile projects to Apache-2.0

### PR DESCRIPTION
**Pull request by l0rd**
### What does this PR do?

We are about to propose Devfile as a CNCF sandbox project. Most of the CNCF projects are licensed under Apache-2.0 and that’s what the community is used to. Re-licensing to Apache-2.0 would make the process smoother and augment our chances to successfully transition the project to CNCF sandbox. Both EPL-2.0 and Apache-2.0 are open source licenses that are widely used in the industry and Apache-2.0 is considered more permissive than EPL-2.0.

⚠️ This PR is in draft mode. We are contacting existing contributors to get their approval and then we will merge it.

### What issues does this PR fix or reference?

https://github.com/devfile/api/issues/426

### CODE REVIEW

**Review by amisevsk — COMMENTED** [review]
It will also be necessary to update https://github.com/devfile/devworkspace-operator/blob/main/hack/boilerplate.go.txt

After this is done, we'll need to update license headers on all files as well -- this will be tricky as the license tool we use won't erase the old EPL license headers. I can look into this.

**Comment by l0rd** [comment]
I have updated the PR to include the change to boilerplate.go.txt too.

We have the approval from all contributors so this PR is ready to merge now.

**Comment by amisevsk** [comment]
> I have updated the PR to include the change to boilerplate.go.txt too.

To make the go license tool happy, we'll need to run `make fmt_license`, but first we'll need to strip license headers from all files (who's good at writing awk scripts?)

**Comment by sleshchenko** [comment]
Append a fix for generated go code

**Review by sleshchenko — APPROVED** [review]

**Pull request merged**
