### PR TITLE
Update project to use Go 1.20

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Update DWO actions/CI to use Go 1.20

### What issues does this PR fix or reference?
Follow on from https://github.com/devfile/devworkspace-operator/pull/1206 that got lost when that PR was closed.

### Is it tested? How?
N/A

### PR Checklist

- [ ] E2E tests pass (when PR is ready, comment `/test v8-devworkspace-operator-e2e, v8-che-happy-path` to trigger)
    - [ ] `v8-devworkspace-operator-e2e`: DevWorkspace e2e test
    - [ ] `v8-che-happy-path`: Happy path for verification integration with Che

### CODE REVIEW

**Comment by amisevsk** [comment]
Depends on https://github.com/devfile/devworkspace-operator/pull/1209 being merged first, then a rebase.

**Review by AObuchow — APPROVED** [review]

**Pull request merged**
